draw_set_color(c_black);
draw_set_alpha(0.3 + (sin(current_time / 500) * 0.1 + 0.1));
draw_rectangle(x - 25, y - 25, x + 25, y + 25, false);
draw_set_alpha(1);
draw_set_color(c_red);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_text(x, y, "⬇");
draw_set_color(c_black);
draw_text(x, y + 30, "DROP HERE");