status_tutorial = 1;
texto_guia = "Talk to 5 merchants and buy a Coke from each.";
fade_alpha = 0;
fade_estado = "fade_in";
player_hp = 100;
player_max_hp = 100;
total_inimigos_p4 = 3;
letreiro_x = 0;
letreiro_velocidade = 2;
inv_shift_x = 0;
npcs_falados = 0;
total_npcs_p1 = 5;
inventario_aberto = false;
itens_coletados = 0;
item_arrastado_index = -1;
itens_removidos_count = 0;
modo_combate = false;
menu_aberto = false;
menu_y_anim = -1080;
aba_selecionada = 0;
menu_opcao_vertical = 0;
sub_menu_estado = "normal";
menu_save_tipo = "carregar";
slot_selecionado = 0;
slot_inv_selecionado = 0;
item_sub_opcao = 0;
foco_aba = true;
delay_entrada = 0;
delay_submenu = 0;
exibir_popup = false;
cooldown_atual = 0;
cooldown_maximo = 60;
dano_mostrar = 0;
dano_timer = 0;
zoom_ataque_alvo = 1.0;
zoom_ataque_atual = 1.0;
fullscreen = false;
audio_volume = 1.0;
achievements_enabled = true;
moedas = 100;
round_atual = 0;
comerciantes_falados = 0;
total_comerciantes = 5;
mostrar_round = false;
round_timer = 0;
caixas_encaixadas = 0;
loja_aberta = false;
loja_npc = noone;
loja_selecao = 0;
loja_itens = [];
loja_precos = [];
loja_nomes = [];
loja_sprites = [];
loja_alpha = 0;
loja_scale = 0.5;

ini_open("configuracoes.ini");
fullscreen = ini_read_real("Video", "Fullscreen", false);
audio_volume = ini_read_real("Audio", "Volume", 1.0);
achievements_enabled = ini_read_real("Gameplay", "Achievements", true);
ini_close();
window_set_fullscreen(fullscreen);
audio_master_gain(audio_volume);

if (!audio_is_playing(snd_tutorial)) audio_play_sound(snd_tutorial, 10, true);
if (!variable_global_exists("fonteNormal")) global.fonteNormal = -1;

ResetScene(1);